#!/bin/bash
rpm -Uvh https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
yum update -y
yum install -y ntp puppet-agent
echo "puppet  puppet-master.dev.local" >> /etc/hosts
systemctl start puppet
systemctl enable puppet
